# Task 1:
bread_price = 1.79
peanut_butter_price = 2.29
jelly_price = 2.95

total_cost = bread_price + peanut_butter_price + jelly_price
print(f"The total cost of bread, peanut better, and jelley is: ${total_cost:.2f}")

# Task 2:
bank_balance = 10000
interest_rate = 0.07
final_balance = bank_balance + (bank_balance * interest_rate)
print(f"The total balance in the account after one year is: ${final_balance:.2f}")
